version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0
workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  aws-cli:
    jobs:
      - create-stack:
          filters:
            branches:
              only: master
          
          
jobs:
  create-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: 
          name: syncing files to s3 and deploying the CFT's 
          no_output_timeout: 50m
          command: |
            echo "Incoming Commit from Branch : ${CIRCLE_BRANCH}"
            aws s3 sync . s3://${SYNC_BUCKET_NAME} --exclude ".gitignore" --exclude ".git/*" --exclude ".circleci/*"
            echo "Template files pushed to git repo"
            aws s3api get-object --bucket ${SYNC_BUCKET_NAME} --key parameters.json parameters.json
            pip install -r requirements.txt
            python deploy_stacks.py
