version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0
workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          filters:
            branches:
              only: master
          # context: aws
          
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: 
          name: Sync to s3
          command: |
            echo "Incoming Commit from Branch : ${CIRCLE_BRANCH}"
            aws s3 sync . s3://${SYNC_BUCKET_NAME} --exclude ".gitignore" --exclude ".git/*" --exclude ".circleci/*"
            echo "Template files pushed to git repo"
  # build:
  #   docker:
  #     - image: circleci/python:3.6
  
  # deploy:
  #    docker: # Specify executor for running deploy job
  #      - image: circleci/python:3.6 # Specify docker image to use
  #    steps:
  #       - run: # Deploy to S3 using the sync commansd
  #           name: Deploy to S3
  #           command: aws s3 sync . s3://aws-cloudformation-templates-cf