---
    AWSTemplateFormatVersion: 2010-09-09
    Description: Creates a Glue Database, Crawler and Security Configuration.
    Parameters: 
      CrawlerName:
        Type: String
      DATABASENAME: 
        Type: String
        Default: glue_database
        Description: The name of the Metadata Database you want to use. It will create if doesn't exist
      CDCDatabaseName:
        Type: String
        Default: s3_dev_kinesis_delivery_database
        Description: If you're using crawler for cdc data.
      CDCTableName:
        Type: String
        Default: s3_dev_cdc_table
        Description: If you're using crawler for cdc data.
      SERVICEROLEARN: 
        Type: String
        Default: service-role-arn
        Description: The IAM service role to use to run the job
      KMSARN:
        Type: String
        Description: ARN to the KMS key to encrypt the uploaded files
      TypeOfConnectionToCrawl:
        Type: String
        AllowedValues: 
          - table
          - s3
        Default: s3
        Description: Should the ConnectionInformation Array have S3 or cdc info?
      S3ConnectionInformation: 
        Type: String
        Description: bucketname/prefix
        Default: None  
      COMPANYNAME: 
        AllowedPattern: ^[a-z]+([a-z-]*[a-z])*$
        ConstraintDescription: Company name can include lowercase letters and hyphens (-). 
          It cannot start or end with a hyphen (-).
        Default: s3
        Description: "S3 bucket naming conventions for the company the stuff is all for"
        Type: String  
      OWNER:
        Type: String
        Default: Jacob Puthuparambil
        Description: enter the 'owner' tag value
      ENVIRONMENT: 
        Type: String    
        AllowedValues:
        - dev
        - qa
        - staging
        - production
        
      ProjectName:
        Type: String
        Description: Name of the project
        Default: datalake 
      TypeofZone:
        Type: String
        AllowedValues:
          - raw
          - transient
          - refined
          - cdc
          - refined_updates
    Conditions:
        CDCTableCrawler: !Equals
            - !Ref TypeOfConnectionToCrawl   
            - table
        PlainS3DataCrawler: !Or
          - !Equals  
            - !Ref TypeofZone   
            - raw
          - !Equals
            - !Ref TypeofZone
            - transient
        Dataclassifier: !Equals
            - !Ref TypeofZone
            - raw
        RefinedCrawler: !Equals
            - !Ref TypeofZone
            - refined
        isGlueDatabase: !Not
            - !Equals
              - !Ref TypeOfConnectionToCrawl
              - table
        RefinedUpdates: !Equals
          - !Ref TypeofZone
          - refined_updates
    Resources:
        DataSecurityConfiguration:
            Type: AWS::Glue::SecurityConfiguration
            Properties: 
                EncryptionConfiguration: 
                    S3Encryptions: 
                    - S3EncryptionMode: SSE-KMS
                      KmsKeyArn: !Ref KMSARN    
                    CloudWatchEncryption:
                        CloudWatchEncryptionMode: SSE-KMS
                        KmsKeyArn: !Ref KMSARN         
                Name: !Sub "${CrawlerName}-Security"
        GlueDatabase:
            Condition: isGlueDatabase
            Type: AWS::Glue::Database
            Properties:
                CatalogId: !Ref AWS::AccountId
                DatabaseInput:
                    Description: !Sub "glue database for ${ProjectName}"
                    Name: !Sub '${DATABASENAME}_${ENVIRONMENT}'
        Classifier:
            Condition: Dataclassifier
            Type: AWS::Glue::Classifier
            Properties: 
                CsvClassifier:
                    ContainsHeader: PRESENT
                    Delimiter: '|'
                    Name: PipeClassifier-${ENVIRONMENT}-${ProjectName}
                    QuoteSymbol: '"'
        S3rawDataCrawler:
            Condition: PlainS3DataCrawler
            Type: AWS::Glue::Crawler
            Properties:
                Name: !Ref CrawlerName
                Classifiers:
                    - !If [Dataclassifier, !Ref Classifier, !Ref 'AWS::NoValue']
                Role: !Ref SERVICEROLEARN
                DatabaseName: !Ref GlueDatabase
                CrawlerSecurityConfiguration: !Ref DataSecurityConfiguration
                Targets: 
                    S3Targets: 
                        - Path: !Ref S3ConnectionInformation
                SchemaChangePolicy:
                    UpdateBehavior: "UPDATE_IN_DATABASE"
                    DeleteBehavior: "DEPRECATE_IN_DATABASE"
                Tags: 
                    Owner: !Sub '${OWNER} - ${COMPANYNAME}'
                    Environment: !Ref ENVIRONMENT
        CDCCrawler:
            Condition: CDCTableCrawler
            Type: AWS::Glue::Crawler
            Properties:
                Name: !Ref CrawlerName
                Role: !Ref SERVICEROLEARN
                CrawlerSecurityConfiguration: !Ref DataSecurityConfiguration
                Targets: 
                    CatalogTargets:
                        - DatabaseName: !Ref CDCDatabaseName
                          Tables: 
                            - !Ref CDCTableName                  
                SchemaChangePolicy:
                    UpdateBehavior: "UPDATE_IN_DATABASE"
                    DeleteBehavior: "LOG"
                Tags: 
                    Owner: !Sub '${OWNER} - ${COMPANYNAME}'
                    Environment: !Ref ENVIRONMENT

        S3refinedAuditDataCrawler:
            Condition: RefinedCrawler
            Type: AWS::Glue::Crawler
            Properties:
                Name: !Ref CrawlerName
                Role: !Ref SERVICEROLEARN
                DatabaseName: !Ref GlueDatabase
                CrawlerSecurityConfiguration: !Ref DataSecurityConfiguration
                Configuration: 
                  !Sub | 
                    {
                    "Version": 1.0,
                    "Grouping": {
                    "TableGroupingPolicy": "CombineCompatibleSchemas" }
                    }
                Targets: 
                    S3Targets:
                        - Path: !Sub '${S3ConnectionInformation}t_baseid/'
                        - Path: !Sub '${S3ConnectionInformation}t_demographic/'
                        - Path: !Sub '${S3ConnectionInformation}t_demographic_survey/'
                        - Path: !Sub '${S3ConnectionInformation}t_demographic_survey_attribute/'
                        - Path: !Sub '${S3ConnectionInformation}t_demographic_survey_value/'
                        - Path: !Sub '${S3ConnectionInformation}t_demographic_tag/'
                        - Path: !Sub '${S3ConnectionInformation}t_demographic_tag_attribute/'
                        - Path: !Sub '${S3ConnectionInformation}t_demographic_tag_value/'
                        - Path: !Sub '${S3ConnectionInformation}t_subscribed_offer/'
                        - Path: !Sub '${S3ConnectionInformation}t_visited_affiliate/'
                SchemaChangePolicy:
                    UpdateBehavior: "UPDATE_IN_DATABASE"
                    DeleteBehavior: "DEPRECATE_IN_DATABASE"
                TablePrefix: 'fig_'
                Tags: 
                    Owner: !Sub '${OWNER} - ${COMPANYNAME}'
                    Environment: !Ref ENVIRONMENT
        S3RefinedUpdatesDataCrawler:
            Condition: RefinedUpdates
            Type: AWS::Glue::Crawler
            Properties:
                Name: !Ref CrawlerName
                Role: !Ref SERVICEROLEARN
                DatabaseName: !Ref GlueDatabase
                CrawlerSecurityConfiguration: !Ref DataSecurityConfiguration
                Configuration: 
                  !Sub | 
                    {
                    "Version": 1.0,
                    "Grouping": {
                    "TableGroupingPolicy": "CombineCompatibleSchemas" }
                    }
                Targets: 
                    S3Targets:
                        - Path: !Sub '${S3ConnectionInformation}t_demographic_cdc_update/'
                        - Path: !Sub '${S3ConnectionInformation}t_demographic_survey_cdc_update/'
                        - Path: !Sub '${S3ConnectionInformation}t_demographic_tag_cdc_update/'
                SchemaChangePolicy:
                    UpdateBehavior: "UPDATE_IN_DATABASE"
                    DeleteBehavior: "DEPRECATE_IN_DATABASE"
                TablePrefix: 'fig_'
                Tags: 
                    Owner: !Sub '${OWNER} - ${COMPANYNAME}'
                    Environment: !Ref ENVIRONMENT            
    Outputs:
        GlueDatabaseName:
            Value: !If [isGlueDatabase,!Ref GlueDatabase,"None"]
        CrawlerName:
            Value: !If [RefinedCrawler,!Ref S3refinedAuditDataCrawler,!If [PlainS3DataCrawler,!Ref S3rawDataCrawler,"None"]]
        RefinedUpdatesCrawler:
          Value: !If [RefinedUpdates, !Ref S3RefinedUpdatesDataCrawler, "None"]