---
    AWSTemplateFormatVersion: 2010-09-09
    Description: Creates a Glue Job and Security COnfiguration
    Parameters: 
        NAME: 
            Type: String
            Default: job-name
            Description: The name of the Glue Job you want to create
        AWSGlueJobRole: 
            Type: String
            Default: service-role-arn
            Description: The IAM service role to use to run the job
        KMSARN:
            Type: String
            Description: ARN to the KMS key to encrypt the uploaded files
        ScriptPath: 
            Type: String
            Description: The S3 location of the Job Path
        TempDirectory:
            Type: String
            Description: The S3 location of the temp directory
        InputDatabase: 
            Type: String
            Description: The database name for the input of the job
        InputTable: 
            Type: String
            Description: The table name for the input of the job
        OutputBucket: 
            Type: String
            Description: The Bucket name for the target of the glue job
        OutputPath: 
            Type: String
            Description: The path/prefix for the output 
        COMPANYNAME: 
            AllowedPattern: ^[a-z]+([a-z-]*[a-z])*$
            ConstraintDescription: Company name can include lowercase letters and hyphens (-). It cannot start or end with a hyphen (-).
            Default: fluent
            Description: "S3 bucket naming conventions for the company the stuff is all for"
            Type: String  
        OWNER:
            Type: String
            Default: Jacob Puthuparambil 
            Description: enter the 'owner' tag value
        ENVIRONMENT: 
            Type: String    
            AllowedValues:
            - dev
            - staging
            - qa
            - production
        ProjectName:
            Type: String
            Description: Name of the project
            Default: datalake
        FirstSource:
            Type: String
            Description: Source of the Data
            Default: None           
        TypeOfJob:
            Type: String
            Description: Type of the Glue Job
            AllowedValues:
                - plain
                - cdc
                - plain_refined
            Default: plain
        TypeOfOperation:
            Type: String
            Description: Operation type of CDC Job
            AllowedValues:
                - update
                - insert
            Default: insert
        SnsArn:
            Type: String
            Default: "None"
        WORKFLOWID:
            Type: String
            Default: "None"
        DpuCount:
            Type: Number
            Default: 30
        WorkerType:
            Type: String
            AllowedValues:
                - Standard
                - G.1X
                - G.2X
            Default: Standard
    
    Conditions:
        CDCJob: !Equals
            - !Ref TypeOfJob
            - cdc
        CDCUpdateOperation: !Equals
            - !Ref TypeOfOperation
            - update
        PlainRefinedJob: !Equals
            - !Ref TypeOfJob
            - plain_refined
        PlainJob: !Equals
            - !Ref TypeOfJob
            - plain
        NonStandardWorker: !Or
          - !Equals  
            - !Ref WorkerType   
            - G.1X
          - !Equals
            - !Ref WorkerType
            - G.2X
        StandardWorker: !Equals
            - !Ref WorkerType
            - Standard

    Resources:
        DataSecurityConfiguration:
            Type: AWS::Glue::SecurityConfiguration
            Properties: 
                EncryptionConfiguration: 
                    S3Encryptions: 
                        - S3EncryptionMode: SSE-KMS
                          KmsKeyArn: !Ref KMSARN     
                    CloudWatchEncryption:
                        CloudWatchEncryptionMode: SSE-KMS
                        KmsKeyArn: !Ref KMSARN  
                Name: !Sub "${NAME}-Security"
        
        GlueJob:
            Type: "AWS::Glue::Job"
            Condition: StandardWorker
            Properties:
                Role: !Ref AWSGlueJobRole
                GlueVersion: '1.0'
                Command: 
                    Name: glueetl
                    PythonVersion: 3
                    ScriptLocation: !Ref ScriptPath
                DefaultArguments: {
                        "--TempDir": !Ref TempDirectory,
                        "--job-bookmark-option": !If [PlainJob, job-bookmark-disable, job-bookmark-enable],
                        "--job-language": "python",
                        "--enable-metrics": "true",
                        "--enable-continuous-cloudwatch-log": "true",
                        "--enable-continuous-log-filter": "false", 
                        "--AWS_REGION": !Sub "${AWS::Region}",
                        "--input_database": !Ref InputDatabase,
                        "--input_table": !Ref InputTable,
                        "--output_bucket": !Ref OutputBucket,
                        "--output_path": !Ref OutputPath,
                        "--sns_arn": !Ref SnsArn,
                        "--first_source": !If [PlainRefinedJob,!Ref FirstSource,None],
                        "--GLUE_ROLE": !If [PlainRefinedJob,!Ref AWSGlueJobRole,None],
                        "--WORKFLOW_ID": !Ref WORKFLOWID,
                        "--operation": !If [CDCJob,!If [CDCUpdateOperation,"update","insert"],None]
                    }
                MaxCapacity: !Ref DpuCount
                # WorkerType: !If [NonStandardWorker,!Ref 'AWS::NoValue', !Ref WorkerType]
                # NumberOfWorkers: !If [NonStandardWorker, !Ref DpuCount,!Ref 'AWS::NoValue']
                Name: !Sub '${ProjectName}-${ENVIRONMENT}-${NAME}' 
                MaxRetries: 0
                Description: !Sub 'Glue Job ${NAME} for ${COMPANYNAME} that reads from ${ScriptPath}'
                SecurityConfiguration: !Ref DataSecurityConfiguration
                Timeout: 2880
                Tags: 
                    Name: !Sub '${ProjectName}-${ENVIRONMENT}-${NAME}'
                    Owner: !Sub '${OWNER}-${COMPANYNAME}'
                    ENVIRONMENT: !Ref ENVIRONMENT

        GlueJobNonStandardWorkerType:
            Type: "AWS::Glue::Job"
            Condition: NonStandardWorker
            Properties:
                Role: !Ref AWSGlueJobRole
                GlueVersion: '1.0'
                Command: 
                    Name: glueetl
                    PythonVersion: 3
                    ScriptLocation: !Ref ScriptPath
                DefaultArguments: {
                        "--TempDir": !Ref TempDirectory,
                        "--job-bookmark-option": !If [PlainJob, job-bookmark-disable, job-bookmark-enable],
                        "--job-language": "python",
                        "--enable-metrics": "true",
                        "--enable-continuous-cloudwatch-log": "true",
                        "--enable-continuous-log-filter": "false", 
                        "--AWS_REGION": !Sub "${AWS::Region}",
                        "--input_database": !Ref InputDatabase,
                        "--input_table": !Ref InputTable,
                        "--output_bucket": !Ref OutputBucket,
                        "--output_path": !Ref OutputPath,
                        "--sns_arn": !Ref SnsArn,
                        "--first_source": !If [PlainRefinedJob,!Ref FirstSource,None],
                        "--GLUE_ROLE": !If [PlainRefinedJob,!Ref AWSGlueJobRole,None],
                        "--WORKFLOW_ID": !Ref WORKFLOWID,
                        "--operation": !If [CDCJob,!If [CDCUpdateOperation,"update","insert"],None]
                    }
                # MaxCapacity: !If [NonStandardWorker,!Ref 'AWS::NoValue', !Ref DpuCount]
                WorkerType: !Ref WorkerType
                NumberOfWorkers: !Ref DpuCount
                Name: !Sub '${ProjectName}-${ENVIRONMENT}-${NAME}' 
                MaxRetries: 0
                Description: !Sub 'Glue Job ${NAME} for ${COMPANYNAME} that reads from ${ScriptPath}'
                SecurityConfiguration: !Ref DataSecurityConfiguration
                Timeout: 2880
                Tags: 
                    Name: !Sub '${ProjectName}-${ENVIRONMENT}-${NAME}'
                    Owner: !Sub '${OWNER}-${COMPANYNAME}'
                    ENVIRONMENT: !Ref ENVIRONMENT


    Outputs: 
      GlueJob: 
        Description: 'Glue Job'
        Value: !If [NonStandardWorker,!Ref GlueJobNonStandardWorkerType ,!Ref GlueJob]  