AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secret for storing th DB credentials'
Parameters: 
    ENVIRONMENT: 
        Type: String    
        AllowedValues:
        - dev
        - qa
        - staging
        - production
    COMPANYNAME: 
        AllowedPattern: ^[a-z]+([a-z-]*[a-z])*$
        ConstraintDescription: Company name can include lowercase letters and hyphens (-). It cannot start or end with a hyphen (-).
        Default: s3
        Description: "Naming conventions for the company"
        Type: String  
    OWNER:
        Type: String
        Default: Jacob Puthuparambil
        Description: enter the 'owner' tag value
    ProjectName:
        Type: String
        Description: Name of the project
        Default: datalake
    Username:
        Type: String
        Description: Username of the Database
        Default: awsdatalake
    Password:
        Type: String
        NoEcho: true
        Description: Password of the Database
    Engine:
        Type: String
        Description: Engine type of the Database
        Default: mysql
    Host:
        Type: String
        Description: Host IP of the Database
        Default: 0.0.0.0
    Port:
        Type: String
        Description: Port number of the Database
        Default: 3306
    DBName: 
        Type: String
        Description: Name of the Database
        Default: db_name
    KmsKeyId:
        Type: String
        Description: ID of the KMS key.
Resources:
    DBSecret:
        Type: 'AWS::SecretsManager::Secret'
        Properties:
            Name: !Sub '${ProjectName}-Secret-${ENVIRONMENT}-${AWS::AccountId}'
            Description: This secret contains DB credentials.
            KmsKeyId: !Ref KmsKeyId
            SecretString: !Sub |
                {
                    "username": "${Username}",
                    "password": "${Password}",
                    "engine": "${Engine}",
                    "host": "${Host}",
                    "port": "${Port}",
                    "dbname": "${DBName}"
                }
            Tags: 
                - Key: "Owner"
                  Value: !Sub '${OWNER} - ${COMPANYNAME}'
                - Key: "Name"
                  Value: !Sub '${ProjectName}-Secret-${ENVIRONMENT}-${AWS::AccountId}'
                - Key: "Environment"
                  Value: !Ref ENVIRONMENT
Outputs:
    DBSecretArn:
        Description: Arn of the DB secret.
        Value: !Ref DBSecret